### ISSUE TITLE
Error en carga de Notas Parciales

### ISSUE THREAD

**Issue by pzamberlan** [InstitutoPascal/campuswebpro#159]
El error ocurre cuando hay mas de un alumno en la lista, y solo se le quiere poner nota a uno de ellos.
Además no se puede poner ausente si uno de los alumnos no participo en alguno de los exámenes.

El controlador es el siguiente

@auth.requires_login()
@auth.requires_membership(role='Docentes')
def examenes_parciales():
    response.title="Docentes"
    response.subtitle="Examenes parciales"
    COMISIONID= (request.args[0])
    q = db.alumnos.alumnoid==db.inscripcionescomision.alumnoid
    q &= db.comisiones.comisionid==COMISIONID
    #q &= db.comisiones.materiaid==db.examenes.materiaid
	#q &=db.inscripcionesexamen.alumnoid==db.alumnos.alumnoid
	# Busca las comisiones que coincidan
    q &= db.inscripcionescomision.condicion == condicion_inscripcion.get ('regular')
    q &= db.inscripcionescomision.comisionid ==  db.comisiones.comisionid
	#q &= db.inscripcionesexamen.examenid == db.examenes.examenid
    q &= db.comisiones.materiaid == db.materias.materiaid
    filas=db(q).select(db.alumnos.ALL,db.comisiones.materiaid, orderby=db.alumnos.nombre, distinct=True)
    i=0
    a=0
    if request.vars.GRABAR:
        for fila in filas:
            if request.vars.condicion=="1":
                calificacion=3 #PARCIAL
                periodo=condicion_periodo.get ('1 cuatri 2015')
            elif request.vars.condicion=="2":
                calificacion=3 #PARCIAL
                periodo=condicion_periodo.get ('2 cuatri 2015')
            elif request.vars.condicion=="1r":
                calificacion=4 #RECUPERATORIO
                periodo=condicion_periodo.get ('1 cuatri 2015')
            elif request.vars.condicion=="2r":
                calificacion=4 #RECUPERATORIO
                periodo=condicion_periodo.get ('2 cuatri 2015')
            fecha= request.vars.fecha
            alumno_id= fila.alumnos.alumnoid
            materiaid=fila.comisiones.materiaid
			#materia_id = alumno.materiaid
			# calificacion_id = 1
            nota = int(request.vars.get("NOTA_%s" % alumno_id, 0))
			# libro = request.vars.libro
			# folio =request.vars.folio
			#observaciones= request.vars.get("observaciones_%s" % alumno_id, 0)
            establecimiento= "I.S.T.B.P"
            a=5
            db.notas.insert(alumnoid=alumno_id, materiaid=materiaid, periodoid=periodo, calificacionid=calificacion, nota=nota ,fecha=fecha, establecimiento=establecimiento)
            i= i+1
    return{'filas':filas,'a':a}

A continuación se adjuntan imágenes:

Captura de pantalla de la vista de carga de notas

![pantalla examenes parciales](https://cloud.githubusercontent.com/assets/11861508/12007011/ce8b9fcc-abce-11e5-809a-83764e2882d5.png)

Error al ingresar una sola  nota:

![error al ingresar una sola nota](https://cloud.githubusercontent.com/assets/11861508/12007019/73b5c536-abcf-11e5-879e-55679a817f99.png)

Para poder ponerle ausente a los alumnos intente crear una función en donde si la nota era 0 que muestre 'ausente' si no que devuelva la nota.

y en cuanto al error de no poder cargar a un solo alumno teniendo varios en la lista, creo que el error se debe a que el controlador siempre nos exige devolver un valor, no puede ser nulo pero no se como modificarla.

**Comment by reingart** [comment]
El [ticket](https://200.80.10.81:44310/admin/default/ticket/campuswebpro/186.129.16.29.2015-12-27.18-52-01.e4690f9b-14fa-49ac-a948-be755a4e42fe) de error indica que no puede convertir un string vacio '' (casillero sin completar) a un valor numérico (int):

> ```
> Traceback (most recent call last):
>  File "/home/www-data/web2py/gluon/restricted.py", line 224, in restricted
    exec ccode in environment
>  File "/home/www-data/web2py/applications/campuswebpro/controllers/docentes.py", line 859, in <module>
>  File "/home/www-data/web2py/gluon/globals.py", line 392, in <lambda>
>    self._caller = lambda f: f()
>  File "/home/www-data/web2py/gluon/tools.py", line 3439, in f
>    return action(*a, **b)
>  File "/home/www-data/web2py/gluon/tools.py", line 3439, in f
>    return action(*a, **b)
>  File "/home/www-data/web2py/applications/campuswebpro/controllers/docentes.py", line 383, in examenes_parciales
>    nota = int(request.vars.get("NOTA_%s" % alumno_id, 0))
> ValueError: invalid literal for int() with base 10: ''
> ```

No es un problema de web2py, simplemente hay que validar los datos sean numéricos (ya que no es un formulario tradicional de web2py SQLFORM).
Se soluciona con una verificación previa a la conversión, por ej:

```python
# obtengo valor del casillero
nota = request.vars.get("NOTA_%s" % alumno_id, '')
# verifico que no esté vacio y sea un número válido:
if nota != '' and nota.isdigit():
    nota = int(nota)   # convierto a valor numérico
else:
    nota = None        # reemplazo por un valor null
```

**Comment by pzamberlan** [comment]
Se utilizo el mismo código para validar las notas finales:
```python
nota = request.vars.get("NOTA_%s" % alumno_id, '')
            # verifico que no esté vacio y sea un número válido:
            if nota != '' and nota.isdigit():
                nota = int(nota)   # convierto a valor numérico
            else:
                nota = None        # reemplazo por un valor null
```
